# Settings for /sell multipliers.

# Whether to stack multipliers and ignore values
# this allows you to place multipliers in groups and stack them
# Example: 'sell.multiplier.god', 'sell.multiplier.quartz', 'sell.multiplier.opulent' will stack
sell-multiplier-stacking:
  enable: false
  # Ever multiplier in the stacking uses this base value.
  # Example: 'sell.multiplier.god' has a base-value of 1.05
  # adding 'sell.multiplier.quartz' will result in a multiplier of 1.10
  # since base value is 1.05 for each stacked multiplier
  base-value: 1.05

# Give multipliers to players with the permissions 'sell.multiplier.{multiplier}'
# Example: 'sell.multiplier.i', 'sell.multiplier.ii'.
# You can add as many multipliers as you want.
# Use the 'default' name to set the default multiplier that everyone has. It defaults to 1 if not set.
# If a player has more than one multiplier permission, it will pick the highest one.

# enable-sell-multiplier-stacking must be set to false for this to work.
sell-multipliers:
  default: 1.0 # NOT a permission. The default multiplier everyone has.
  i: 1.10
  ii: 1.20
  iii: 1.30
  iiii: 1.40
  v: 1.50

# Message sent to player when sell multiplier has been applied.
# Will not send a message for 'default', or if player possesses none of the specified permissions above.
# First %s is the (highest) permission the player has, as specified above - such as 'v'.
# Second %s is the dollar amount.
# Example: Blessing of the Oracle (V) has given you an extra ($15.00) Denarii!
message: §dBlessing of the Oracle (%s) has given you an extra §c($%s) §dDenarii!