name: SellMultiplier
version: 1.0.3
main: com.sellmultiplier.SellMultiplier
author: bfrisco
description: Sell Hand Multiplier
api-version: 1.18
depend: [Essentials]

commands:
  sellmultiplier:
    description: Reloads configuration
    usage: ยง7/sellmultiplier reload, ยง7/sellmultiplier check <player>
  multiplier:
    description: Gives player their sell hand multiplier
    usage: ยง7/multiplier