name: SellMultiplier
version: 1.0.2
main: com.sellmultiplier.SellMultiplier
author: bfrisco
description: Sell Hand Multiplier
api-version: 1.18
depend: [Essentials]

commands:
  sellmultiplier:
    description: Reloads configuration
    usage: ยง7/sellmultiplier reload